version: 0.1.0

project: locobot-push-demo

jobs:
  demo:
    type: test
    package:
      docker:
        build:
          dockerfile: ./Dockerfile
    runtime:
      simulator: gazebo:11
      framework: ros2:humble
    scenarios:
      settings:
        - name: collision
          ros_testfile: src/collision_test.py
