version: 0.1.0

project: artefacts-interbotix-movit2

jobs:
  demo:
    type: test
    package:
      docker:
        build:
          dockerfile: ./Dockerfile
    runtime:
      simulator: gazebo:11
      framework: ros2:humble
    scenarios:
      settings:
        - name: full
          run: ros2 run artefacts_demo_control artefacts_control
        - name: joints
          run: ros2 run artefacts_demo_control ex_joint_goal
        - name: gripper
          run: ros2 run artefacts_demo_control ex_gripper_command
