version: 0.1.0

project: artefacts-interbotix-movit2

jobs:
  demo:
    type: test
    package:
      docker:
        build:
          dockerfile: ./Dockerfile
    runtime:
      simulator: gazebo:11
      framework: ros2:humble
    scenarios:
      settings:
        - name: full
          ros_testfile: artefacts_demo_control/collision_test.py
